name: med_kit
description: Your medicine scanner application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  fluttertoast: ^8.0.8
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  cloud_firestore: ^2.4.0
  firebase_storage: ^10.0.1
  image_picker: ^0.8.3+2

  flutter_lints: ^2.0.0

flutter:
  assets:
  - assets/images/ #Multiple Images will be included. @@ Author Egemen

  fonts:
    - family: RobotoCondensed
      fonts:
       - asset: assets/fonts/RobotoCondensed-Regular.ttf


  uses-material-design: true